## Importing Libraries

In [ ]:
#Importing Libraries with their short forms for easy use
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing Datasets with Pandas

In [ ]:
#Importing dataset with help of pandas
dataset= pd.read_csv("Data.csv") #Would create DataFrame of the dataset, which is a 2dim spreadSheet


### (i) Dependent Variable would be in Last Coloumn
### (ii) Independent Variable coloumn would be rest which are the features of the model

In [ ]:
#For input variable: X
#Now X variable would takes the input/independent features and Y would take the dependent Var
X=dataset.iloc[:,:-1].values #.values because to get the datasets in the form of numpyArray
#iloc: "locating index"(same as arrrayIndexing) comes under Pandas, First argument is for rows and {:} represents all elements and Second arg is for coloumns
#Here in 2nd Arg: {:} is all elements and -1, indicates the range->(total-1) which gives the index till of the last coloumn as indexing starts from 0, and upper bound is not considered in the range in python leaving last coloumn , all are considered
#Any substraction and addition or any Arethmatic will give the range of the elements and bydefault upperbound discarded and
#(-1) is by-default the index of last-coloumn
print(X)



[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
#For output variable : Y
#Same for getting the Y-values{dependent} from dataset, we need the whole rows for including all the datapoints and needed only last coloumn which is dependent variable, so -1 indicates the index of the last coloumn
Y=dataset.iloc[:,-1].values
#Y1=Y.reshape(-1,1)
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Working with missing Values
### * After every import the package is always a class and while using them we add "()" at their end as they have constructor, default

In [ ]:
#Working on missing data using scikit-learn
#For numerical missing value, any specific value could be placed there
from sklearn.impute import SimpleImputer #Sklearn.impute is "module" and SimpleImputer is a "class"
imputer = SimpleImputer(missing_values=np.nan,strategy='mean') #New object(imputer) is made from that class(simpleimputer), and the class contained the parameterised constructor in order to pass the value for using the class
#Above First argument is for which is targeted: here is missing values are targeted from numpy and Second Argument is for the value would come on the place of targeted value, here "mean" of the respective coloumn would come.

#Now lets impliement the above object to the input matrix X:
imputer.fit(X[:,1:3]) # For all rows and for only 1st and 2nd coloumns for replacing the missing values arefitted here
X[:,1:3]=imputer.transform(X[:,1:3]) # Returns the specific coulumns with mean intilised in the missing values and here tranformation occurs
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding of the string elements in X, here order doesnot required between them, so going with HotEncoding

In [ ]:
#We could also assign the numerical values like 1,2,3.. for the strings but the ML Model in future would correlate as the strings have relation with each other, so we are encoding the strings such a way that there should not be a relationship among them
#Hot-Encoding
from sklearn.compose import ColumnTransformer # Used for tansforming into encodes
from sklearn.preprocessing import OneHotEncoder # Encoding type, That is HOtEncoding
ct= ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
#For transformer: 1-Arg= Which kind of transformation that is Encoding
                 # 2-Arg= Which Encoding that HotEncoding
                 # 3-Arg which indexs want we to encode: col-index number
#For remainder=passthourgh: If not applied, then hot encoding done from 0 to secondlast col by default

#Now lets connect the above object with the input-Matrix X:
#Unlike for missing value diferent steps for fitting and tranforming, here module has both in one
X=np.array(ct.fit_transform(X)) #ct.fit_trans donot returns the matrix into numpy array but X dataset should be numpyArray
print(X)#The resultant replacement by the dummyVaraibles

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


###(*) Basically what happend above, the string value are considered as categorialValues and in above examplte we have 3 categeries as a string : France, Spain , Germany which would generate DummyVariables
###(*) So, replacing countryCol, added 3-new-columns, with same countryName
###(*) Datapoint containg the respective column, get '1' under the respective CountryNamed col and rest get 0
###    France     Germany    Spain
### (1)  1       0      0  == France
### (2)  0       0      1  == Spain
### Similarly Goes on...

# (***)Dummy_Variable Trap, when we have n categorialColumns as in above example n is 3, then we should include only n-1 dummyVariable inside the equation of straightLine as assuming the defaultState as the state of the left-dummyVar, if not then defaultState is not deined and model would give some error.

## Encoding Dependent Variable Y, in which order matters, so going with labelEncoder


In [ ]:
# Here in dependent variable we would only encode the yes or no nothing much comlicated, only 0 and 1
from sklearn.preprocessing import LabelEncoder #For that using labelEncoder mainly for binaryType Encoding (Yes or No)
le=LabelEncoder()
Y=le.fit_transform(Y)# Dependent variable vector doesnot have to have numpy Array
Y


array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

### And for Y , we have only 2 categorialValues or String Values, so by taking only one column any of dummyVariable we could consider both,, as dummyVariable act as switches means "1" refers yes to first categroy else to 2nd category that is "0"

### We have to impliment the Feature Scaling after the splitting the training and testing dataset beacuse to prevent the leakage of data from test set to training set until the training has not been done, as the test data should be new and had no relation with training set

## Splitting the datasets


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(X,Y,test_size=0.2,random_state=1) #80-20
#test size=0.2: decides random 20% of dataset going to the testSet
#random_state=1: decides every time same split happens
print(X_train)
print()
print(X_test)
print()
print(Y_train)
print()
print(Y_test)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]

[0 1 0 0 1 1 0 1]

[0 1]


## **Feature Scaling:**
 ### 1) **Standard Deviation**: Range[-3,3]
 ### * Can used all the time, versatile in nature
 ### * Recommadation is this!!!
        Xsd = x-mean(x)/SD(x)
 ### 2) **Normalisation**: Range[0,1]:
 ### * Used when only most of the features have same and normal disctribution
         Xnorm = x-min(x)/max(x)-min(x)  

## FS shouldnot be appliend on the encoded dummyVariable of the strings as their interpretation of repective string would be lost

In [ ]:
# Implimented StandardDeviation as FeatureScale
from sklearn.preprocessing import StandardScaler # For feautureScaling
sc= StandardScaler()
#We donot have to scale the first-3 coloumns as they are hotEncoded and only included 'Age' and 'salary'
#Below Included age and salary coloumn as not upperBound so goes till end that is salaryCol {Only 2 columns included}
X_train[:,3:]=sc.fit_transform(X_train[:,3:])
print(X_train)
X_test[:,3:]=sc.fit_transform(X_test[:,3:])
print(X_test)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]
[[0.0 1.0 0.0 -1.0 -1.0]
 [1.0 0.0 0.0 1.0 1.0]]


# **FeatureScaling is not applied in Simple_LR, MultiVar_LR and Polynomial_LR ; Because the coefficient of the input features/independentVariable will determine their capacity as predictor in the prediction, so that is upto the co-efficients**